Vagrant.configure("2") do |config|
  #config.vm.box = "centos/8"
  #config.vm.box_version = "1911.1"
  config.vm.box = "centos/8"
  config.vm.box_url = "http://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.1.1911-20200113.3.x86_64.vagrant-virtualbox.box"
end
