# -*- mode: ruby -*-
# vi: set ft=ruby :


##############
### References
# - https://www.vagrantup.com/docs/vagrantfile/machine_settings.html
# - https://www.vagrantup.com/docs/vagrantfile/tips.html
# - https://www.vagrantup.com/docs/networking/forwarded_ports.html
##############

#unless Vagrant.has_plugin?("HostManager")
#  raise 'HostManager plugin not installed!'
#end

require 'digest/sha1'

uniqID = "_" + (Digest::SHA1.hexdigest Dir.pwd()).slice(0..8)
image  = "ubuntu/xenial64"
#image = "centos/7"

if Vagrant::Util::Platform.windows? then
  interfaces = [
    "Intel(R) 82583V Gigabit Network Connection",
    "Intel(R) 82579LM Gigabit Network Connection",
  ]
elsif Vagrant::Util::Platform.darwin? then
  interfaces = [
    "en0: Wi-Fi (AirPort)",
    "en1: Wi-Fi (AirPort)",
  ]
else
  interfaces = [
    "eth0",
    "eth1",
    "wlan0",
  ]
end


Vagrant.configure("2") do |config|
  vboxName1 = "box-101"
  hostname1 = "box101"
  config.vm.define "#{vboxName1}" do |front|
    front.vm.box = "#{image}"
    #front.vm.network :private_network, ip: "192.168.56.101"
    front.vm.network :public_network, use_dhcp_assigned_default_route: true, bridge: interfaces
    front.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "#{hostname1}#{uniqID}"]
    end
  end
  vboxName2 = "box-102"
  hostname2 = "box102"
  config.vm.define "#{vboxName2}" do |front|
    front.vm.box = "#{image}"
    #front.vm.network :private_network, ip: "192.168.56.102"
    front.vm.network :public_network, use_dhcp_assigned_default_route: true, bridge: interfaces
    front.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "#{hostname2}#{uniqID}"]
    end
  end
end
